version: '3.8'

services:
  jiex-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jiex-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
